CREATE TABLE IF NOT EXISTS teacher_salary_advances (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id integer NOT NULL UNIQUE REFERENCES teacher_salary_requests(id) ON DELETE CASCADE,
  school_id integer NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount numeric(12,2) NOT NULL CHECK (amount > 0),
  deduction_month varchar(20) NOT NULL,
  deduction_year integer NOT NULL,
  remarks text,
  status varchar(20) NOT NULL DEFAULT 'approved' CHECK (status IN ('approved', 'applied')),
  salary_id integer REFERENCES teacher_salaries(id) ON DELETE SET NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE teacher_salary_requests
  ADD COLUMN IF NOT EXISTS advance_percentage numeric(5,2);

CREATE INDEX IF NOT EXISTS idx_teacher_salary_advances_due
  ON teacher_salary_advances (school_id, teacher_id, deduction_year, deduction_month)
  WHERE status = 'approved';
